[build]
builder = "nixpacks"
buildCommand = "prisma generate && next build"

[deploy]
startCommand = "prisma db push && npm run db:seed && npm run start"
healthcheckPath = "/"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
