[build]
builder = "nixpacks"
buildCommand = "prisma generate && next build && cp -r .next/static .next/standalone/.next/static && cp -r public .next/standalone/public"

[deploy]
startCommand = "prisma db push && npm run db:seed && node .next/standalone/server.js"
healthcheckPath = "/"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
